import {
   COMMON_DC_SUGGESTIONS,
   DARKNESS_MODE,
   DEFAULT_MOVEMENT_ACTIONS,
   GRANT_TRIGGER_OPTIONS,
   SURFACE_MODE,
   TARGET_OPTIONS,
   getMovementActionOptions,
} from "./constants.mjs"
import {
   actorExclusionFields,
   triggerTargetFields,
} from "./behavior-field-groups.mjs"
import { getEnvironmentTypeOptions } from "./options.mjs"

export const BEHAVIOR_CATALOG = [
   {
      type: "adjustDarknessLevel",
      label: "PF2EATW.Behavior.AdjustDarknessLevel",
      icon: "fa-solid fa-moon",
      events: [],
      fields: [
         {
            key: "mode",
            type: "select",
            valueType: "number",
            label: "PF2EATW.Field.DarknessMode",
            options: [
               {
                  value: DARKNESS_MODE.OVERRIDE,
                  label: "PF2EATW.DarknessMode.Override",
               },
               {
                  value: DARKNESS_MODE.BRIGHTEN,
                  label: "PF2EATW.DarknessMode.Brighten",
               },
               {
                  value: DARKNESS_MODE.DARKEN,
                  label: "PF2EATW.DarknessMode.Darken",
               },
            ],
            default: DARKNESS_MODE.OVERRIDE,
         },
         {
            key: "modifier",
            type: "range",
            label: "PF2EATW.Field.DarknessModifier",
            min: 0,
            max: 1,
            step: 0.05,
            default: 0.5,
         },
      ],
   },
   {
      type: "modifyMovementCost",
      label: "PF2EATW.Behavior.ModifyMovementCost",
      icon: "fa-solid fa-shoe-prints",
      events: [],
      fields: [
         {
            key: "preset",
            type: "select",
            label: "PF2EATW.Field.TerrainPreset",
            options: [
               { value: "difficult", label: "PF2EATW.Terrain.Difficult" },
               {
                  value: "greaterDifficult",
                  label: "PF2EATW.Terrain.GreaterDifficult",
               },
               { value: "custom", label: "PF2EATW.Terrain.Custom" },
            ],
            default: "difficult",
         },
         {
            key: "customCost",
            type: "number",
            label: "PF2EATW.Field.CustomCost",
            default: 2,
            min: 1,
            step: 0.5,
            dependsOn: { preset: "custom" },
         },
         {
            key: "actions",
            type: "tagPicker",
            label: "PF2EATW.Field.AffectedActions",
            addPrompt: "PF2EATW.Field.AddMovementAction",
            options: getMovementActionOptions,
            default: DEFAULT_MOVEMENT_ACTIONS,
         },
         ...actorExclusionFields(),
      ],
   },
   {
      type: "defineSurface",
      label: "PF2EATW.Behavior.Environment",
      icon: "fa-solid fa-mountain",
      events: [],
      fields: [
         {
            key: "environment",
            type: "tagPicker",
            label: "PF2EATW.Field.EnvironmentTypes",
            addPrompt: "PF2EATW.Field.AddEnvironmentType",
            hint: "PF2EATW.Field.EnvironmentTypesHint",
            options: getEnvironmentTypeOptions,
            default: [],
         },
         {
            key: "mode",
            type: "select",
            valueType: "number",
            label: "PF2EATW.Field.SurfaceMode",
            options: [
               { value: SURFACE_MODE.ADD, label: "PF2EATW.SurfaceMode.Add" },
               {
                  value: SURFACE_MODE.REMOVE,
                  label: "PF2EATW.SurfaceMode.Remove",
               },
               {
                  value: SURFACE_MODE.OVERRIDE,
                  label: "PF2EATW.SurfaceMode.Override",
               },
            ],
            default: SURFACE_MODE.ADD,
         },
      ],
   },
   {
      type: "environmentFeature",
      label: "PF2EATW.Behavior.EnvironmentFeature",
      icon: "fa-solid fa-tree",
      events: [],
      fields: [
         {
            key: "difficultTerrain",
            type: "select",
            label: "PF2EATW.Field.DifficultTerrain",
            options: [
               { value: "none", label: "PF2EATW.PF2eDT.None" },
               { value: "difficult", label: "PF2EATW.PF2eDT.Difficult" },
               {
                  value: "greaterDifficult",
                  label: "PF2EATW.PF2eDT.GreaterDifficult",
               },
            ],
            default: "difficult",
         },
      ],
   },
   {
      type: "applyActiveEffect",
      label: "PF2EATW.Behavior.ApplyActiveEffect",
      icon: "fa-solid fa-sparkles",
      events: ["tokenEnter"],
      fields: [
         {
            key: "uuid",
            type: "uuidInput",
            label: "PF2EATW.Field.EffectUuid",
            placeholder: "Compendium.pf2e.equipment-effects.Item.xxxxxxxx",
            default: "",
         },
         ...triggerTargetFields(["tokenEnter"], GRANT_TRIGGER_OPTIONS),
      ],
   },
   {
      type: "removeEffect",
      label: "PF2EATW.Behavior.RemoveEffect",
      icon: "fa-solid fa-sparkles",
      events: ["tokenEnter"],
      fields: [
         {
            key: "uuid",
            type: "uuidInput",
            label: "PF2EATW.Field.EffectUuid",
            placeholder: "Compendium.pf2e.equipment-effects.Item.xxxxxxxx",
            default: "",
         },
         ...triggerTargetFields(["tokenEnter"], GRANT_TRIGGER_OPTIONS),
      ],
   },
   {
      type: "addCondition",
      label: "PF2EATW.Behavior.AddCondition",
      icon: "fa-solid fa-skull-crossbones",
      events: ["tokenEnter"],
      fields: [
         {
            key: "condition",
            type: "conditionPicker",
            label: "PF2EATW.Field.Condition",
            default: { slug: "frightened", value: 1 },
         },
         {
            key: "duration",
            type: "duration",
            label: "PF2EATW.Field.Duration",
            tooltip: "PF2EATW.Tooltip.Duration",
            default: { enabled: false, amount: 1, unit: "rounds" },
         },
         ...triggerTargetFields(["tokenEnter"], GRANT_TRIGGER_OPTIONS),
      ],
   },
   {
      type: "removeCondition",
      label: "PF2EATW.Behavior.RemoveCondition",
      icon: "fa-solid fa-skull-crossbones",
      events: ["tokenEnter"],
      fields: [
         {
            key: "condition",
            type: "conditionPicker",
            label: "PF2EATW.Field.Condition",
            default: { slug: "frightened", value: 1 },
         },
         ...triggerTargetFields(["tokenEnter"], GRANT_TRIGGER_OPTIONS),
      ],
   },
   {
      type: "applyRuleElement",
      label: "PF2EATW.Behavior.ApplyRuleElement",
      icon: "fa-solid fa-code",
      events: ["tokenEnter"],
      fields: [
         {
            key: "label",
            type: "text",
            label: "PF2EATW.Label",
            default: "",
         },
         {
            key: "rules",
            type: "ruleElementList",
            label: "PF2EATW.Field.RuleElements",
            default: [],
         },
         {
            key: "duration",
            type: "duration",
            label: "PF2EATW.Field.Duration",
            tooltip: "PF2EATW.Tooltip.Duration",
            default: { enabled: false, amount: 1, unit: "rounds" },
         },
         ...triggerTargetFields(["tokenEnter"], GRANT_TRIGGER_OPTIONS),
      ],
   },
   {
      type: "dealDamage",
      label: "PF2EATW.Behavior.DealDamage",
      icon: "fa-solid fa-burst",
      events: ["tokenEnter"],
      fields: [
         {
            key: "damages",
            type: "damageList",
            label: "PF2EATW.Field.Damages",
            default: [
               {
                  diceCount: 1,
                  dieSize: "d6",
                  damageType: "fire",
                  category: "normal",
               },
            ],
         },
         ...triggerTargetFields(["tokenEnter"]),
      ],
   },
   {
      type: "rollDice",
      label: "PF2EATW.Behavior.RollDice",
      icon: "fa-solid fa-dice",
      events: ["tokenEnter"],
      fields: [
         {
            key: "dice",
            type: "diceFormula",
            label: "PF2EATW.Field.Dice",
            default: { diceCount: 1, dieSize: 20 },
         },
         {
            key: "consequences",
            type: "consequenceList",
            label: "PF2EATW.Field.Consequences",
            default: [],
         },
         ...triggerTargetFields(["tokenEnter"]),
      ],
   },
   {
      type: "savingThrow",
      label: "PF2EATW.Behavior.SavingThrow",
      icon: "fa-solid fa-shield-halved",
      events: ["tokenEnter"],
      fields: [
         {
            key: "save",
            type: "select",
            label: "PF2EATW.Field.SaveType",
            options: [
               { value: "fortitude", label: "PF2EATW.Save.Fortitude" },
               { value: "reflex", label: "PF2EATW.Save.Reflex" },
               { value: "will", label: "PF2EATW.Save.Will" },
            ],
            default: "reflex",
         },
         {
            key: "dc",
            type: "expressionWithSuggestions",
            label: "PF2EATW.Field.DC",
            tooltip: "PF2EATW.Tooltip.ExpressionDC",
            suggestions: COMMON_DC_SUGGESTIONS,
            default: "15",
         },
         {
            key: "basicSave",
            type: "boolean",
            label: "PF2EATW.Field.BasicSave",
            tooltip: "PF2EATW.Tooltip.BasicSave",
            default: false,
         },
         {
            key: "basicDamages",
            type: "damageList",
            label: "PF2EATW.Field.BasicSaveDamages",
            showWhen: { field: "basicSave", equals: true },
            default: [
               {
                  diceCount: 1,
                  dieSize: "d6",
                  damageType: "fire",
                  category: "normal",
               },
            ],
         },
         {
            key: "extraRollOptions",
            type: "extraRollOptions",
            label: "PF2EATW.Field.AppendRollOptions",
            tooltip: "PF2EATW.Tooltip.AppendRollOptions",
            default: { enabled: false, value: "" },
         },
         {
            key: "consequences",
            type: "saveConsequenceList",
            label: "PF2EATW.Field.Consequences",
            default: [],
         },
         ...triggerTargetFields(["tokenEnter"]),
      ],
   },
   {
      type: "rollSkill",
      label: "PF2EATW.Behavior.RollSkill",
      icon: "fa-solid fa-dice-d20",
      events: ["tokenEnter"],
      fields: [
         {
            key: "skill",
            type: "select",
            label: "PF2EATW.Field.SkillType",
            options: [
               { value: "acrobatics", label: "PF2EATW.Skill.Acrobatics" },
               { value: "arcana", label: "PF2EATW.Skill.Arcana" },
               { value: "athletics", label: "PF2EATW.Skill.Athletics" },
               { value: "crafting", label: "PF2EATW.Skill.Crafting" },
               { value: "deception", label: "PF2EATW.Skill.Deception" },
               { value: "diplomacy", label: "PF2EATW.Skill.Diplomacy" },
               { value: "intimidation", label: "PF2EATW.Skill.Intimidation" },
               { value: "medicine", label: "PF2EATW.Skill.Medicine" },
               { value: "nature", label: "PF2EATW.Skill.Nature" },
               { value: "occultism", label: "PF2EATW.Skill.Occultism" },
               { value: "performance", label: "PF2EATW.Skill.Performance" },
               { value: "religion", label: "PF2EATW.Skill.Religion" },
               { value: "society", label: "PF2EATW.Skill.Society" },
               { value: "stealth", label: "PF2EATW.Skill.Stealth" },
               { value: "survival", label: "PF2EATW.Skill.Survival" },
               { value: "thievery", label: "PF2EATW.Skill.Thievery" },
               { value: "perception", label: "PF2EATW.Skill.Perception" },
               { value: "lore", label: "PF2EATW.Skill.Lore" },
            ],
            default: "athletics",
         },
         {
            key: "lore",
            type: "text",
            label: "PF2EATW.Field.LoreName",
            placeholder: "PF2EATW.Field.LoreNamePlaceholder",
            showWhen: { field: "skill", equals: "lore" },
            default: "",
         },
         {
            key: "dc",
            type: "expressionWithSuggestions",
            label: "PF2EATW.Field.DC",
            tooltip: "PF2EATW.Tooltip.ExpressionDC",
            suggestions: COMMON_DC_SUGGESTIONS,
            default: "15",
         },
         {
            key: "extraRollOptions",
            type: "extraRollOptions",
            label: "PF2EATW.Field.AppendRollOptions",
            tooltip: "PF2EATW.Tooltip.AppendRollOptions",
            default: { enabled: false, value: "" },
         },
         {
            key: "consequences",
            type: "saveConsequenceList",
            label: "PF2EATW.Field.Consequences",
            default: [],
         },
         ...triggerTargetFields(["tokenEnter"]),
      ],
   },
   {
      type: "choiceSet",
      label: "PF2EATW.Behavior.ChoiceSet",
      icon: "fa-solid fa-list-check",
      events: ["tokenEnter"],
      fields: [
         {
            key: "choices",
            type: "choiceList",
            label: "PF2EATW.Field.Choices",
            default: [],
         },
         {
            key: "consequences",
            type: "saveConsequenceList",
            label: "PF2EATW.Field.Consequences",
            default: [],
         },
         ...triggerTargetFields(["tokenEnter"]),
      ],
   },
   {
      type: "sendChatMessage",
      label: "PF2EATW.Behavior.SendChatMessage",
      icon: "fa-solid fa-comment-dots",
      events: ["tokenEnter"],
      fields: [
         {
            key: "text",
            type: "textarea",
            label: "PF2EATW.Field.ChatMessageText",
            placeholder: "PF2EATW.Field.ChatMessagePlaceholder",
            default: "",
         },
         {
            key: "privateToGm",
            type: "boolean",
            label: "PF2EATW.Field.PrivateToGm",
            tooltip: "PF2EATW.Tooltip.PrivateToGm",
            mutuallyExclusiveWith: "blindToGm",
            default: false,
         },
         {
            key: "blindToGm",
            type: "boolean",
            label: "PF2EATW.Field.BlindToGm",
            tooltip: "PF2EATW.Tooltip.BlindToGm",
            mutuallyExclusiveWith: "privateToGm",
            default: false,
         },
         ...triggerTargetFields(["tokenEnter"]),
      ],
   },
   {
      type: "addIRW",
      label: "PF2EATW.Behavior.AddIRW",
      icon: "fa-solid fa-shield-virus",

      events: ["tokenEnter", "tokenExit"],
      fields: [
         {
            key: "immunities",
            type: "tagPicker",
            label: "PF2EATW.Field.WallImmunities",
            addPrompt: "PF2EATW.Field.AddImmunity",
            options: "damageTypeOptions",
            default: [],
         },
         {
            key: "resistances",
            type: "irwTagList",
            label: "PF2EATW.Field.WallResistances",
            addPrompt: "PF2EATW.Field.AddResistance",
            default: [],
         },
         {
            key: "weaknesses",
            type: "irwTagList",
            label: "PF2EATW.Field.WallWeaknesses",
            addPrompt: "PF2EATW.Field.AddWeakness",
            default: [],
         },

         {
            key: "target",
            type: "tagPicker",
            label: "PF2EATW.Field.Target",
            addPrompt: "PF2EATW.Field.AddTarget",
            hint: "PF2EATW.Field.TargetHint",
            options: TARGET_OPTIONS,
            default: ["all"],
            emptyFallback: ["all"],
            tooltip: "PF2EATW.Tooltip.TargetDefault",
         },
         ...actorExclusionFields(),
      ],
   },
   {
      type: "attachTile",
      label: "PF2EATW.Behavior.AttachTile",
      icon: "fa-solid fa-image",
      events: [],
      fields: [
         {
            key: "tiles",
            type: "tileList",
            label: "PF2EATW.Field.TileEditor",
            default: [],
         },
         {
            key: "scale",
            type: "range",
            label: "PF2EATW.Field.TileScale",
            min: 0.1,
            max: 1,
            step: 0.05,
            default: 1,
         },
         {
            key: "preserveAspectRatio",
            type: "boolean",
            label: "PF2EATW.Field.TilePreserveAspectRatio",
            tooltip: "PF2EATW.Tooltip.TilePreserveAspectRatio",
            default: false,
         },
      ],
   },
   {
      type: "attachSound",
      label: "PF2EATW.Behavior.AttachSound",
      icon: "fa-solid fa-volume-high",
      events: [],
      fields: [
         {
            key: "sound",
            type: "soundEditor",
            label: "PF2EATW.Field.SoundEditor",
            default: {},
         },
         {
            key: "radiusBoost",
            type: "range",
            label: "PF2EATW.Field.SoundRadiusBoost",
            tooltip: "PF2EATW.Tooltip.SoundRadiusBoost",
            min: -0.9,
            max: 2,
            step: 0.05,
            displayAs: "percent",
            default: 0,
         },
      ],
   },
   {
      type: "attachLight",
      label: "PF2EATW.Behavior.AttachLight",
      icon: "fa-solid fa-lightbulb",
      events: [],
      fields: [
         {
            key: "light",
            type: "lightEditor",
            label: "PF2EATW.Field.LightEditor",
            default: {},
         },
      ],
   },
   {
      type: "attachWalls",
      label: "PF2EATW.Behavior.AttachWalls",
      icon: "fa-solid fa-border-all",
      events: [],
      fields: [
         {
            key: "move",
            type: "select",
            valueType: "number",
            label: "PF2EATW.Field.WallMove",
            options: [
               { value: 0, label: "PF2EATW.WallMove.None" },
               { value: 20, label: "PF2EATW.WallMove.Normal" },
            ],
            default: 20,
         },
         {
            key: "light",
            type: "select",
            valueType: "number",
            label: "PF2EATW.Field.WallLight",
            options: [
               { value: 0, label: "PF2EATW.WallSense.None" },
               { value: 20, label: "PF2EATW.WallSense.Normal" },
               { value: 10, label: "PF2EATW.WallSense.Limited" },
            ],
            default: 20,
         },
         {
            key: "sight",
            type: "select",
            valueType: "number",
            label: "PF2EATW.Field.WallSight",
            options: [
               { value: 0, label: "PF2EATW.WallSense.None" },
               { value: 20, label: "PF2EATW.WallSense.Normal" },
               { value: 10, label: "PF2EATW.WallSense.Limited" },
               { value: 30, label: "PF2EATW.WallSense.Proximity" },
               { value: 40, label: "PF2EATW.WallSense.Distance" },
            ],
            default: 20,
         },
         {
            key: "sound",
            type: "select",
            valueType: "number",
            label: "PF2EATW.Field.WallSound",
            options: [
               { value: 0, label: "PF2EATW.WallSense.None" },
               { value: 20, label: "PF2EATW.WallSense.Normal" },
               { value: 10, label: "PF2EATW.WallSense.Limited" },
            ],
            default: 20,
         },
         {
            key: "dir",
            type: "select",
            valueType: "number",
            label: "PF2EATW.Field.WallDir",
            options: [
               { value: 0, label: "PF2EATW.WallDir.Both" },
               { value: 1, label: "PF2EATW.WallDir.Left" },
               { value: 2, label: "PF2EATW.WallDir.Right" },
            ],
            default: 0,
         },
         {
            key: "singleWall",
            type: "boolean",
            label: "PF2EATW.Field.SingleWall",
            tooltip: "PF2EATW.Tooltip.SingleWall",
            default: false,
         },
         {
            key: "destroyable",
            type: "boolean",
            label: "PF2EATW.Field.WallDestroyable",
            tooltip: "PF2EATW.Tooltip.WallDestroyable",
            default: false,
         },
         {
            key: "destroyableHP",
            type: "number",
            label: "PF2EATW.Field.WallDestroyableHP",
            showWhen: { field: "destroyable", equals: true },
            default: 30,
         },
         {
            key: "destroyableAC",
            type: "number",
            label: "PF2EATW.Field.WallDestroyableAC",
            showWhen: { field: "destroyable", equals: true },
            default: 15,
         },
         {
            key: "destroyableHardness",
            type: "number",
            label: "PF2EATW.Field.WallDestroyableHardness",
            showWhen: { field: "destroyable", equals: true },
            default: 5,
         },
         {
            key: "destroyableActorSize",
            type: "number",
            label: "PF2EATW.Field.WallDestroyableActorSize",
            tooltip: "PF2EATW.Tooltip.WallDestroyableActorSize",
            showWhen: { field: "destroyable", equals: true },
            default: 10,
         },
         {
            key: "wallImmunities",
            type: "tagPicker",
            label: "PF2EATW.Field.WallImmunities",
            addPrompt: "PF2EATW.Field.AddImmunity",
            options: "damageTypeOptions",
            showWhen: { field: "destroyable", equals: true },
            default: [],
         },
         {
            key: "wallResistances",
            type: "irwTagList",
            label: "PF2EATW.Field.WallResistances",
            addPrompt: "PF2EATW.Field.AddResistance",
            showWhen: { field: "destroyable", equals: true },
            default: [],
         },
         {
            key: "wallWeaknesses",
            type: "irwTagList",
            label: "PF2EATW.Field.WallWeaknesses",
            addPrompt: "PF2EATW.Field.AddWeakness",
            showWhen: { field: "destroyable", equals: true },
            default: [],
         },
         {
            key: "wallHasStrike",
            type: "boolean",
            label: "PF2EATW.Field.WallHasStrike",
            tooltip: "PF2EATW.Tooltip.WallHasStrike",
            showWhen: { field: "destroyable", equals: true },
            default: false,
         },
         {
            key: "wallStrikeName",
            type: "text",
            label: "PF2EATW.Field.WallStrikeName",
            placeholder: "PF2EATW.Field.WallStrikeNamePlaceholder",
            showWhen: { field: "wallHasStrike", equals: true },
            default: "",
         },
         {
            key: "wallStrikeAttack",
            type: "expressionWithSuggestions",
            label: "PF2EATW.Field.WallStrikeAttack",
            tooltip: "PF2EATW.Tooltip.WallStrikeAttack",
            suggestions: [
               { value: "10", label: "PF2EATW.WallStrikeSuggest.FlatTen" },
               {
                  value: "@placer.system.attributes.spellDC.value - 10",
                  label: "PF2EATW.WallStrikeSuggest.PlacerSpellAttack",
               },
               {
                  value: "@placer.system.attributes.classDC.value - 10",
                  label: "PF2EATW.WallStrikeSuggest.PlacerClassDCMinusTen",
               },
               {
                  value: "@placer.system.attributes.classOrSpellDC.value - 10",
                  label: "PF2EATW.WallStrikeSuggest.PlacerClassOrSpellDCMinusTen",
               },
            ],
            showWhen: { field: "wallHasStrike", equals: true },
            default: "10",
         },
         {
            key: "wallStrikeDamages",
            type: "damageList",
            label: "PF2EATW.Field.WallStrikeDamages",
            showWhen: { field: "wallHasStrike", equals: true },
            default: [],
         },
      ],
   },
   {
      type: "playSound",
      label: "PF2EATW.Behavior.PlaySound",
      icon: "fa-solid fa-play",
      events: [],
      fields: [
         {
            key: "src",
            type: "filePicker",
            label: "PF2EATW.Field.SoundFile",
            filePickerType: "audio",
            default: "",
         },
         {
            key: "volume",
            type: "range",
            label: "PF2EATW.Field.Volume",
            min: 0,
            max: 1,
            step: 0.05,
            default: 0.5,
         },
      ],
   },
   {
      type: "displayScrollingText",
      label: "PF2EATW.Behavior.DisplayScrollingText",
      icon: "fa-solid fa-font",
      events: ["tokenEnter"],
      fields: [
         {
            key: "text",
            type: "text",
            label: "PF2EATW.Field.ScrollingText",
            default: "",
         },
         {
            key: "color",
            type: "color",
            label: "PF2EATW.Field.Color",
            default: "#ffffff",
         },
         {
            key: "fontSize",
            type: "number",
            label: "PF2EATW.Field.FontSize",
            default: 28,
            min: 8,
         },
         ...triggerTargetFields(["tokenEnter"]),
      ],
   },
   {
      type: "executeScript",
      label: "PF2EATW.Behavior.ExecuteScript",
      icon: "fa-solid fa-code",
      events: ["tokenEnter"],
      fields: [
         {
            key: "source",
            type: "textarea",
            label: "PF2EATW.Field.Source",
            rows: 6,
            default: "",
         },
         ...triggerTargetFields(["tokenEnter"]),
      ],
   },
   {
      type: "executeMacro",
      label: "PF2EATW.Behavior.ExecuteMacro",
      icon: "fa-solid fa-scroll",
      events: ["tokenEnter"],
      fields: [
         {
            key: "uuid",
            type: "uuidInput",
            label: "PF2EATW.Field.MacroUuid",
            placeholder: "Macro.xxxxxxxx OR Compendium...",
            default: "",
         },
         ...triggerTargetFields(["tokenEnter"]),
      ],
   },
]
